name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: beheardqueue
          entryPoint: './'
          hosting: |
            public: .next
            ignore:
              - firebase.json
              - .firebaserc
              - .git
              - .gitignore
              - node_modules
              - README.md
            rewrites:
              - source: /_next/static/**/**
                destination: /_next/static/**/**
              - source: /_next/image/**/**
                destination: /_next/image/**/**
              - source: /_next/data/**/**
                destination: /_next/data/**/**
              - source: /_next/**/**
                destination: /_next/**/**
              - source: /static/**/**
                destination: /static/**/**
              - source: /favicon.ico
                destination: /favicon.ico
              - source: /manifest.json
                destination: /manifest.json
              - source: /robots.txt
                destination: /robots.txt
              - source: /sitemap.xml
                destination: /sitemap.xml
              - source: /api/**/**
                destination: /api/**/**
              - source: /**/**
                destination: /index.html
          env: |
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY }}
            NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID }}